Repository ut-issl/c2a-aobc, pull requests merged in 2023-07, with the labels that each got.

#120 ActionsをOSS化後に合わせて修正
  .github/workflows/build.yml
Labels: :rocket: priority::high, :wrench: tools

#122 Fix code owner setting
  .github/CODEOWNERS
Labels: :rocket: priority::high, :wrench: tools

#121 各種templateの修正
  .github/ISSUE_TEMPLATE/action_item.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :notebook: documentation, :rocket: priority::high, :wrench: tools

#128 Introduce workflows-c2a
  .github/workflows/.python-version
  .github/workflows/c2a.yml
Labels: :airplane: priority::medium, :wrench: tools, :artificial_satellite: C2A

#125 Add sqrtf function with assertion
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/stt_gyro_ekf.c
  src/src_user/Library/Orbit/kepler_orbit.c
  src/src_user/Library/Orbit/sgp4.c
  src/src_user/Library/c2a_math.c
  src/src_user/Library/c2a_math.h
  src/src_user/Library/geomagnetism.c
  src/src_user/Library/quaternion.c
  src/src_user/Library/time_space.c
  src/src_user/Library/vector3.c
Labels: :bug: bug, :airplane: priority::medium, :dolphin: minor update

#135 Fix typo in README.md
  README.md
Labels: :airplane: priority::medium, :fish: patch

#136 テンプレートを作成後、注意書きを非表示にする
  .github/ISSUE_TEMPLATE/action_item.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :notebook: documentation, :car: priority::low

#86 Bdotでの磁場情報を計測値から推定値に変更
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/bdot.c
Labels: :bug: bug, :airplane: priority::medium, :fish: patch

#134 hotfix/build example with vMicro
  Examples/C2A_AOBC_EXAMPLE.vcxproj
Labels: :bug: bug, :rocket: priority::high, :artificial_satellite: C2A

#138 Main merge to develop for v6.0.2 update
  Examples/C2A_AOBC_EXAMPLE.vcxproj
Labels: :rocket: priority::high, :fish: patch

#76 Support Linux for SILS with WINGS
  CMakeLists.txt
  src/src_user/IfWrapper/CMakeLists.txt
  src/src_user/IfWrapper/SILS/CCSDS_SILS_SCI_IF.c
  src/src_user/IfWrapper/SILS/CCSDS_SILS_SCI_IF.h
  src/src_user/IfWrapper/SILS/uart_sils_sci_if.cpp
  src/src_user/IfWrapper/SILS/uart_sils_sci_if.h
  src/src_user/IfWrapper/Sils/adc_sils.c
  src/src_user/IfWrapper/Sils/com_port.cpp
  src/src_user/IfWrapper/Sils/com_port.h
  src/src_user/IfWrapper/Sils/dc_sils.c
  src/src_user/IfWrapper/Sils/flash_db/.gitkeep
  src/src_user/IfWrapper/Sils/gpio_sils.c
  src/src_user/IfWrapper/Sils/i2c_sils.c
  src/src_user/IfWrapper/Sils/spi_sils.c
  src/src_user/IfWrapper/Sils/uart_sils.cpp
  src/src_user/IfWrapper/Sils/uart_sils.h
  src/src_user/IfWrapper/Sils/wdt_sils.c
  src/src_user/Settings/sils_port_config.h
Labels: :airplane: priority::medium, :dolphin: minor update, :wrench: tools

#139 Modify stt current convention time
  Examples/src_aobc_example/Settings/SatelliteParameters/ina260_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/ina260_parameters.c
Labels: :car: priority::low, :fish: patch

#140 Minor update v6.1.0
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/action_item.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/.python-version
  .github/workflows/actionlint.yml
  .github/workflows/build.yml
  .github/workflows/c2a.yml
  .github/workflows/labeler.yml
  CMakeLists.txt
  Examples/src_aobc_example/Settings/SatelliteParameters/ina260_parameters.c
  README.md
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/bdot.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/fine_three_axis_determination.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/rough_three_axis_determination.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/stt_gyro_ekf.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/sun_vector_propagator.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/ActuatorControllers/mtq_seiren_controller.c
  src/src_user/Applications/UserDefined/AOCS/InertialReference/time_space_calculator.c
  src/src_user/Applications/UserDefined/AOCS/TargetAttitude/target_attitude_calculator.c
  src/src_user/Applications/UserDefined/AOCS/aocs_manager.c
  src/src_user/Applications/UserDefined/AOCS/aocs_manager.h
  src/src_user/Applications/UserDefined/AOCS/aocs_mode_manager.c
  src/src_user/IfWrapper/CMakeLists.txt
  src/src_user/IfWrapper/SILS/CCSDS_SILS_SCI_IF.c
  src/src_user/IfWrapper/SILS/CCSDS_SILS_SCI_IF.h
  src/src_user/IfWrapper/SILS/uart_sils_sci_if.cpp
  src/src_user/IfWrapper/SILS/uart_sils_sci_if.h
  src/src_user/IfWrapper/Sils/adc_sils.c
  src/src_user/IfWrapper/Sils/com_port.cpp
  src/src_user/IfWrapper/Sils/com_port.h
  src/src_user/IfWrapper/Sils/dc_sils.c
  src/src_user/IfWrapper/Sils/flash_db/.gitkeep
  src/src_user/IfWrapper/Sils/gpio_sils.c
  src/src_user/IfWrapper/Sils/i2c_sils.c
  src/src_user/IfWrapper/Sils/spi_sils.c
  src/src_user/IfWrapper/Sils/uart_sils.cpp
  src/src_user/IfWrapper/Sils/uart_sils.h
  src/src_user/IfWrapper/Sils/wdt_sils.c
  src/src_user/Library/Orbit/kepler_orbit.c
  src/src_user/Library/Orbit/sgp4.c
  src/src_user/Library/c2a_math.c
  src/src_user/Library/c2a_math.h
  src/src_user/Library/geomagnetism.c
  src/src_user/Library/quaternion.c
  src/src_user/Library/time_space.c
  src/src_user/Library/vector3.c
  src/src_user/Settings/SatelliteParameters/Sample/ina260_parameters.c
  src/src_user/Settings/sils_port_config.h
Labels: :airplane: priority::medium, :dolphin: minor update

#145 [Hotfix] Add description of body-fixed frame definition
  README.md
Labels: :notebook: documentation, :rocket: priority::high, :fish: patch

#143 [Hotfix] RW I2Cアドレスのデフォルト値をs2e-aobcに合わせる
  Examples/src_aobc_example/Settings/user_defined_i2c_address.h
  src/src_user/Settings/port_config.h
Labels: :rocket: priority::high, :fish: patch

#146 Merge main to develop for v6.1.1 patch update
  Examples/src_aobc_example/Settings/user_defined_i2c_address.h
  README.md
  src/src_user/Settings/port_config.h
Labels: :airplane: priority::medium, :fish: patch

#144 Add minimum torque limit for unloading
  Examples/src_aobc_example/Settings/SatelliteParameters/attitude_control_parameters.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/unloading.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/unloading.h
  src/src_user/Settings/SatelliteParameters/Sample/attitude_control_parameters.c
  src/src_user/Settings/SatelliteParameters/attitude_control_parameters.h
Labels: :airplane: priority::medium, :dolphin: minor update

#142 Fix initial mode
  database/CMD_DB/ISSL6U_AOBC_CMD_DB_BCT.csv
  src/src_user/Settings/Modes/TaskLists/tl_initial.c
  src/src_user/Settings/Modes/Transitions/sl_initial.c
  src/src_user/Settings/Modes/Transitions/sl_initial.h
  src/src_user/Settings/Modes/mode_definitions.c
  src/src_user/TlmCmd/block_command_definitions.c
  src/src_user/TlmCmd/block_command_definitions.h
  src/src_user/TlmCmd/command_definitions.c
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :airplane: priority::medium, :dolphin: minor update
