Repository ut-issl/c2a-aobc, pull requests merged in 2023-10, with the labels that each got.

#228 CONTROL TLMの修正
  database/TLM_DB/AOBC_TLM_DB_AOBC_ANOMALY.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_AOCS_MANAGER.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_CONTROL.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_ANOMALY.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_AOCS_MANAGER.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_CONTROL.csv
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :airplane: priority::medium, :whale: major update

#229 Sun sensor angle TLMの追加
  database/TLM_DB/AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_COMPONENTS.csv
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :airplane: priority::medium, :whale: major update

#230 Fix OPS files
  database/CmdPlan/AOBC_ANOMALY.ops
  database/CmdPlan/AOBC_AOCS_MANAGER.ops
  database/CmdPlan/AOBC_BDOT.ops
  database/CmdPlan/AOBC_BIAS.ops
  database/CmdPlan/AOBC_DR.ops
  database/CmdPlan/AOBC_EH.ops
  database/CmdPlan/AOBC_FINE_THREE_AXIS_DETERMINATION.ops
  database/CmdPlan/AOBC_MODE_MANAGER.ops
  database/CmdPlan/AOBC_MPU9250.ops
  database/CmdPlan/AOBC_MPU9250_FILTER.ops
  database/CmdPlan/AOBC_MPU9250__FILTER.ops
  database/CmdPlan/AOBC_MTQ_CONTROLLER.ops
  database/CmdPlan/AOBC_OC_EH.ops
  database/CmdPlan/AOBC_OEM7600.ops
  database/CmdPlan/AOBC_OEM7600_FILTER.ops
  database/CmdPlan/AOBC_ORBIT.ops
  database/CmdPlan/AOBC_RANG_TLM_MODE.ops
  database/CmdPlan/AOBC_RM3100_FILTER.ops
  database/CmdPlan/AOBC_RM3100__FILTER.ops
  database/CmdPlan/AOBC_ROUGH_THREE_AXIS_DETERMINATION.ops
  database/CmdPlan/AOBC_RW0003.ops
  database/CmdPlan/AOBC_RW0003_FILTER.ops
  database/CmdPlan/AOBC_SAGITTA_FILTER.ops
  database/CmdPlan/AOBC_STIM210.ops
  database/CmdPlan/AOBC_STIM210_FILTER.ops
  database/CmdPlan/AOBC_STT_GYRO_EKF.ops
  database/CmdPlan/AOBC_SUNSENSOR_SELECTOR.ops
  database/CmdPlan/AOBC_SUN_POINTING.ops
  database/CmdPlan/AOBC_SUN_SENSOR_FILTER.ops
  database/CmdPlan/AOBC_SUN_SENSOR_SELECTOR.ops
  database/CmdPlan/AOBC_THREE_AXIS_MTQ.ops
  database/CmdPlan/AOBC_THREE_AXIS_RW.ops
  src/src_user/Applications/UserDefined/Thermal/temperature_anomaly.c
Labels: :airplane: priority::medium, :whale: major update, :wrench: tools, :satellite: WINGS

#233 Add a method to README to deal with cases where environment building does not work.
  README.md
Labels: :notebook: documentation, :airplane: priority::medium, :fish: patch

#232 Add and modify Cubewheel files
  src/src_user/Applications/DriverInstances/di_cube_wheel.c
  src/src_user/Applications/DriverInstances/di_cube_wheel.h
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/ActuatorControllers/rw_controller.c
  src/src_user/Drivers/Aocs/cube_wheel.c
  src/src_user/Drivers/Aocs/cube_wheel.h
Labels: :airplane: priority::medium, :dolphin: minor update

#237 GPS時刻スパイクフィルタの追加
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/oem7600_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/oem7600_filter.h
  src/src_user/Applications/UserDefined/AOCS/InertialReference/time_space_calculator.c
  src/src_user/Applications/UserDefined/AOCS/OrbitEstimation/gpsr_orbit_propagator.c
  src/src_user/Library/SignalProcess/spike_filter.c
  src/src_user/Library/SignalProcess/spike_filter.h
  src/src_user/Library/TimeSystem/gps_time.c
  src/src_user/Library/TimeSystem/gps_time.h
  src/src_user/Library/physical_constants.h
  src/src_user/Library/time_space.c
  src/src_user/Library/time_space.h
  src/src_user/Settings/SatelliteParameters/Sample/oem7600_parameters.c
  src/src_user/Settings/SatelliteParameters/oem7600_parameters.h
Labels: :airplane: priority::medium, :dolphin: minor update

#239 Major update v8
  README.md
Labels: :notebook: documentation, :airplane: priority::medium, :whale: major update

#245 add ss check by degree
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorSelectors/sun_sensor_selector.c
  src/src_user/Drivers/Aocs/nanossoc_d60.h
Labels: :airplane: priority::medium, :fish: patch

#243 Update s2e-aobc version to v5.0.0 in CI
  .github/workflows/build.yml
Labels: :airplane: priority::medium, :fish: patch, :wrench: tools

#244 Merge main to develop for hotfix #234
  .github/workflows/build.yml
Labels: :airplane: priority::medium, :fish: patch

#250 SagittaのFirmware update 10.3 -> 10.7対応
  database/CmdPlan/AOBC_SAGITTA_PARAMETER_SET.ops
  database/TLM_DB/AOBC_TLM_DB_AOBC_CONTROL.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_SAGITTA_READ1.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_SAGITTA_READ2.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_SAGITTA_SET1.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_SAGITTA_SET2.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_CONTROL.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_SAGITTA_READ1.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_SAGITTA_READ2.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_SAGITTA_SET1.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_SAGITTA_SET2.csv
  src/src_user/Applications/DriverInstances/di_sagitta.c
  src/src_user/Drivers/Aocs/sagitta.c
  src/src_user/Drivers/Aocs/sagitta.h
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :car: priority::low, :dolphin: minor update

#253 fix bug PIC INA read error
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_ina260.c
Labels: :bug: bug, :airplane: priority::medium, :fish: patch
