Repository ut-issl/c2a-aobc, pull requests merged in 2023-09, with the labels that each got.

#208 [Hotfix] Fix SS state check
  src/src_user/Applications/DriverInstances/di_nanossoc_d60.c
Labels: :bug: bug, :airplane: priority::medium, :fish: patch

#210 Merge main to develop for #208
  src/src_user/Applications/DriverInstances/di_nanossoc_d60.c
Labels: :rocket: priority::high, :fish: patch

#212 [Hotfix] Fix construction procedure of c2a-aobc-example
  Examples/README.md
  README.md
Labels: :notebook: documentation, :rocket: priority::high, :fish: patch

#211 [Hotfix] Fix example of CMake
  Examples/CMakeLists.txt
Labels: :notebook: documentation, :rocket: priority::high, :fish: patch

#214 Merge main to develop for hotfixes
  Examples/CMakeLists.txt
  Examples/README.md
  README.md
Labels: :rocket: priority::high, :fish: patch

#217 [Hotfix] Fix WINGS link in README
  README.md
Labels: :notebook: documentation, :rocket: priority::high, :fish: patch, :satellite: WINGS

#218 Merge main to develop for Hotfix #217
  README.md
Labels: :notebook: documentation, :rocket: priority::high, :fish: patch

#216 cmd db の Cmd_ prefix を削除
  database/CMD_DB/ISSL6U_AOBC_CMD_DB_CMD_DB.csv
  tools/tlm_cmd_gen_config.json
Labels: :airplane: priority::medium, :whale: major update

#221 Remove Example directory
  Examples/C2A_AOBC_EXAMPLE.sln
  Examples/C2A_AOBC_EXAMPLE.vcxproj
  Examples/C2A_AOBC_EXAMPLE.vcxproj.user
  Examples/CMakeLists.txt
  Examples/README.md
  Examples/c2a_aobc_example.filters
  Examples/c2a_aobc_example.ino
  Examples/c2a_aobc_example.user
  Examples/src_aobc_example/.gitkeep
  Examples/src_aobc_example/Settings/SatelliteParameters/attitude_control_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/attitude_determination_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/attitude_target_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/component_selector_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/fdir_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/ina260_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/mpu9250_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/nanossoc_d60_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/oem7600_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/orbit_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/rm3100_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/rw0003_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/sagitta_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/stim210_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/structure_parameters.c
  Examples/src_aobc_example/Settings/user_defined_i2c_address.h
  Examples/src_aobc_example/Settings/user_defined_sensor_number.h
  README.md
Labels: :whale: major update

#223 Delete `Cmd_` prefix from ops files
  database/CmdPlan/AOBC_ANOMALY.ops
  database/CmdPlan/AOBC_AOCS_MANAGER.ops
  database/CmdPlan/AOBC_BDOT.ops
  database/CmdPlan/AOBC_BIAS.ops
  database/CmdPlan/AOBC_DR.ops
  database/CmdPlan/AOBC_EH.ops
  database/CmdPlan/AOBC_FINE_THREE_AXIS_DETERMINATION.ops
  database/CmdPlan/AOBC_FRAME_TRANSFORMATION.ops
  database/CmdPlan/AOBC_HILS.ops
  database/CmdPlan/AOBC_MODE_MANAGER.ops
  database/CmdPlan/AOBC_MPU9250.ops
  database/CmdPlan/AOBC_MPU9250__FILTER.ops
  database/CmdPlan/AOBC_MTQ_CONTROLLER.ops
  database/CmdPlan/AOBC_NVM.ops
  database/CmdPlan/AOBC_OC_EH.ops
  database/CmdPlan/AOBC_OEM7600.ops
  database/CmdPlan/AOBC_OEM7600_FILTER.ops
  database/CmdPlan/AOBC_ORBIT.ops
  database/CmdPlan/AOBC_RANG_TLM_MODE.ops
  database/CmdPlan/AOBC_RM3100__FILTER.ops
  database/CmdPlan/AOBC_ROUGH_THREE_AXIS_DETERMINATION.ops
  database/CmdPlan/AOBC_RW0003.ops
  database/CmdPlan/AOBC_RW0003_FILTER.ops
  database/CmdPlan/AOBC_SAGITTA_FILTER.ops
  database/CmdPlan/AOBC_SAGITTA_PARAMETER_SET.ops
  database/CmdPlan/AOBC_SAGITTA_REAL_SKY_TEST.ops
  database/CmdPlan/AOBC_SAGITTA_TELEMETRY.ops
  database/CmdPlan/AOBC_STIM210.ops
  database/CmdPlan/AOBC_STIM210__FILTER.ops
  database/CmdPlan/AOBC_STT_GYRO_EKF.ops
  database/CmdPlan/AOBC_SUNSENSOR_FILTER.ops
  database/CmdPlan/AOBC_SUNSENSOR_SELECTOR.ops
  database/CmdPlan/AOBC_SUN_POINTING.ops
  database/CmdPlan/AOBC_TARGET_ATTITUDE.ops
  database/CmdPlan/AOBC_THREE_AXIS_MTQ.ops
  database/CmdPlan/AOBC_THREE_AXIS_RW.ops
  database/CmdPlan/AOBC_TIME_SPACE.ops
  database/CmdPlan/AOBC_UNLOADING.ops
Labels: :airplane: priority::medium, :whale: major update, :wrench: tools, :artificial_satellite: C2A

#202 sagitta driver で厳密なフレーム探索を有効化
  src/src_user/Drivers/Aocs/sagitta.c
Labels: :airplane: priority::medium, :dolphin: minor update

#224 WINGSでの表示を綺麗にするためのTLM DB修正
  database/TLM_DB/AOBC_TLM_DB_AOBC_BIAS.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_CONTROL.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_FILTERS_2.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_FRAME_TRANSFORMATION.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_NON_VOLATILE.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_ORBIT.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_POWER.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_SUN_POINTING.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_TEMP_CALIB.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_THREE_AXIS_MTQ.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_THREE_AXIS_RW.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_BIAS.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_CONTROL.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_FILTERS_2.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_FRAME_TRANSFORMATION.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_NON_VOLATILE.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_ORBIT.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_POWER.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_SUN_POINTING.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_TEMP_CALIB.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_THREE_AXIS_MTQ.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_THREE_AXIS_RW.csv
Labels: :airplane: priority::medium, :whale: major update, :satellite: WINGS

#225 Update HK
  database/TLM_DB/AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_HK_ALGO.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_HK_COMPO.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_HK_GEN.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_HK_ALGO.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_HK_COMPO.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_HK_GEN.csv
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :airplane: priority::medium, :whale: major update
