Repository ut-issl/c2a-aobc, pull requests merged in 2023-08, with the labels that each got.

#153 Fix OEM enum to avoid error in c2a-enum loader
  src/src_user/Drivers/Aocs/oem7600.h
Labels: :airplane: priority::medium, :fish: patch, :wrench: tools

#150 Add pytest
  .gitignore
  src/src_user/Test/pytest.ini
  src/src_user/Test/test/.gitkeep
  src/src_user/Test/test/src_core/Applications/test_nop.py
  src/src_user/Test/test/src_user/.gitkeep
  src/src_user/Test/test/src_user/Applications/.gitkeep
  src/src_user/Test/test/src_user/Applications/DriverInstances/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/AttitudeControl/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/HardwareDependent/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/HardwareDependent/ActuatorControllers/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorMonitors/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorSelectors/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/InertialReference/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/OrbitEstimation/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/TargetAttitude/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/AOCS/test_aocs_manager.py
  src/src_user/Test/test/src_user/Applications/UserDefined/Cdh/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/Power/.gitkeep
  src/src_user/Test/test/src_user/Applications/UserDefined/Thermal/.gitkeep
  src/src_user/Test/utils/c2a_enum_utils.py
  src/src_user/Test/utils/wings_utils.py
Labels: :airplane: priority::medium, :dolphin: minor update, :wrench: tools, :artificial_satellite: C2A, :satellite: WINGS

#158 Main merge for Hotfix #153
  src/src_user/Drivers/Aocs/oem7600.h
Labels: :rocket: priority::high, :fish: patch

#137 STTテレメの追加
  database/CmdPlan/AOBC_SAGITTA_TELEMETRY.ops
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_HK_COMPO.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_HK_GEN.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA1.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA2.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA3.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA4.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA_READ2.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_HK_COMPO.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_HK_GEN.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA1.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA2.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA3.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA4.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA_READ2.csv
  src/src_user/Applications/DriverInstances/di_sagitta.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorSelectors/stt_selector.c
  src/src_user/Applications/UserDefined/Thermal/temperature_anomaly.c
  src/src_user/Drivers/Aocs/sagitta.c
  src/src_user/Drivers/Aocs/sagitta.h
  src/src_user/TlmCmd/telemetry_definitions.c
  src/src_user/TlmCmd/telemetry_definitions.h
Labels: :airplane: priority::medium, :whale: major update

#161 Resize the driver receive buffer
  src/src_user/Applications/DriverInstances/di_fm25v10.c
  src/src_user/Applications/DriverInstances/di_ina260.c
  src/src_user/Applications/DriverInstances/di_mobc.c
  src/src_user/Applications/DriverInstances/di_mpu9250.c
  src/src_user/Applications/DriverInstances/di_nanossoc_d60.c
  src/src_user/Applications/DriverInstances/di_oem7600.c
  src/src_user/Applications/DriverInstances/di_rm3100.c
  src/src_user/Applications/DriverInstances/di_rw0003.c
  src/src_user/Applications/DriverInstances/di_stim210.c
  src/src_user/Drivers/Aocs/mpu9250.c
  src/src_user/Drivers/Aocs/nanossoc_d60.c
  src/src_user/Drivers/Aocs/oem7600.c
  src/src_user/Drivers/Aocs/oem7600.h
  src/src_user/Drivers/Aocs/rm3100.c
  src/src_user/Drivers/Aocs/rw0003.c
  src/src_user/Drivers/Aocs/stim210.c
  src/src_user/Drivers/Aocs/stim210.h
  src/src_user/Drivers/Cdh/fm25v10.c
  src/src_user/Drivers/Cdh/fm25v10.h
  src/src_user/Drivers/Etc/mobc.c
  src/src_user/Drivers/Etc/mobc.h
  src/src_user/Drivers/Power/ina260.c
  src/src_user/Settings/DriverSuper/driver_buffer_define.h
  src/src_user/Settings/DriverSuper/driver_super_params.h
Labels: :rocket: priority::high, :dolphin: minor update

#79 GPS時刻関連の更新
  C2A_AOBC.vcxproj
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/oem7600_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorSelectors/gpsr_selector.c
  src/src_user/Applications/UserDefined/AOCS/InertialReference/time_space_calculator.c
  src/src_user/Applications/UserDefined/AOCS/OrbitEstimation/gpsr_orbit_propagator.c
  src/src_user/Applications/UserDefined/AOCS/aocs_manager.c
  src/src_user/Applications/UserDefined/AOCS/aocs_manager.h
  src/src_user/Library/CMakeLists.txt
  src/src_user/Library/time_space.c
  src/src_user/Library/time_space.h
  src/src_user/Library/time_system/gps_time.c
  src/src_user/Library/time_system/gps_time.h
Labels: :bug: bug, :airplane: priority::medium, :dolphin: minor update

#164 GPSRテレメ出力設定CMDのコメントアウト
  database/CMD_DB/ISSL6U_AOBC_CMD_DB_CMD_DB.csv
  src/src_user/TlmCmd/command_definitions.c
  src/src_user/TlmCmd/command_definitions.h
Labels: :airplane: priority::medium, :whale: major update

#163 パラメータの微修正
  Examples/src_aobc_example/Settings/SatelliteParameters/attitude_control_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/nanossoc_d60_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/orbit_parameters.c
  Examples/src_aobc_example/Settings/user_defined_i2c_address.h
  src/src_user/Settings/SatelliteParameters/Sample/attitude_control_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/nanossoc_d60_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/orbit_parameters.c
  src/src_user/Settings/port_config.h
Labels: :rocket: priority::high, :fish: patch

#166 Main merge to develop for #163
  Examples/src_aobc_example/Settings/SatelliteParameters/attitude_control_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/nanossoc_d60_parameters.c
  Examples/src_aobc_example/Settings/SatelliteParameters/orbit_parameters.c
  Examples/src_aobc_example/Settings/user_defined_i2c_address.h
  src/src_user/Settings/SatelliteParameters/Sample/attitude_control_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/nanossoc_d60_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/orbit_parameters.c
  src/src_user/Settings/port_config.h
Labels: :rocket: priority::high, :fish: patch

#162 太陽非可視時に太陽ベクトル伝搬法を追加
  database/CMD_DB/ISSL6U_AOBC_CMD_DB_CMD_DB.csv
  database/CmdPlan/AOBC_ROUGH_THREE_AXIS_DETERMINATION.ops
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_CONTROL.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_CONTROL.csv
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/rough_three_axis_determination.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/rough_three_axis_determination.h
  src/src_user/Settings/SatelliteParameters/Sample/attitude_determination_parameters.c
  src/src_user/Settings/SatelliteParameters/attitude_determination_parameters.h
  src/src_user/TlmCmd/command_definitions.c
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :airplane: priority::medium, :whale: major update

#165 ユーザーが太陽センサ搭載個数を選べるように修正
  Examples/CMakeLists.txt
  Examples/src_aobc_example/Settings/SatelliteParameters/nanossoc_d60_parameters.c
  Examples/src_aobc_example/Settings/user_defined_i2c_address.h
  Examples/src_aobc_example/Settings/user_defined_sensor_number.h
  database/CMD_DB/ISSL6U_AOBC_CMD_DB_CMD_DB.csv
  database/CmdPlan/AOBC_NVM.ops
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_FRAME_TRANSFORMATION.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_HK_COMPO.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_NON_VOLATILE.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_FRAME_TRANSFORMATION.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_HK_COMPO.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_NON_VOLATILE.csv
  src/src_user/Applications/DriverInstances/di_nanossoc_d60.c
  src/src_user/Applications/DriverInstances/di_nanossoc_d60.h
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorSelectors/sun_sensor_selector.c
  src/src_user/Settings/SatelliteParameters/Sample/nanossoc_d60_parameters.c
  src/src_user/Settings/SatelliteParameters/nanossoc_d60_parameters.h
  src/src_user/Settings/System/EventHandlerRules/event_handler_rule_tlmcmd.c
  src/src_user/Settings/System/EventHandlerRules/event_handler_rules.h
  src/src_user/Settings/port_config.h
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_nanossoc_d60.c
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :airplane: priority::medium, :whale: major update

#168 [Hotfix] Typoの一括修正
  src/src_user/Applications/DriverInstances/di_mpu9250.c
  src/src_user/Applications/DriverInstances/di_stim210.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/bdot.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/unloading.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/unloading.h
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/stt_gyro_ekf.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/stt_gyro_ekf.h
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/sun_vector_propagator.h
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/ActuatorControllers/mtq_seiren_controller.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/mpu9250_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/nanossoc_d60_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/oem7600_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/rm3100_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/stim210_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorSelectors/gpsr_selector.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorSelectors/magnetometer_selector.h
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorSelectors/sun_sensor_selector.c
  src/src_user/Applications/UserDefined/AOCS/InertialReference/inertial_geomag_calculator.c
  src/src_user/Applications/UserDefined/AOCS/OrbitEstimation/gpsr_orbit_propagator.c
  src/src_user/Applications/UserDefined/AOCS/TargetAttitude/target_attitude_from_orbit.c
  src/src_user/Applications/UserDefined/AOCS/TargetAttitude/target_attitude_from_orbit.h
  src/src_user/Applications/UserDefined/AOCS/aocs_manager.c
  src/src_user/Applications/UserDefined/AOCS/aocs_manager.h
  src/src_user/Applications/UserDefined/Cdh/non_volatile_memory_manager.h
  src/src_user/Applications/UserDefined/Cdh/non_volatile_memory_parameter.c
  src/src_user/Applications/UserDefined/Power/power_switch_control.c
  src/src_user/Drivers/Aocs/mpu9250.c
  src/src_user/Drivers/Aocs/mpu9250.h
  src/src_user/Drivers/Aocs/mtq_seiren.h
  src/src_user/Drivers/Aocs/oem7600.c
  src/src_user/Drivers/Aocs/oem7600.h
  src/src_user/Drivers/Aocs/rw0003.c
  src/src_user/Drivers/Aocs/sagitta.h
  src/src_user/Drivers/Aocs/stim210.c
  src/src_user/Library/ControlUtility/gyroscopic_effect.h
  src/src_user/Library/Orbit/kepler_orbit.h
  src/src_user/Library/SignalProcess/spike_filter.c
  src/src_user/Library/SignalProcess/z_filter.c
  src/src_user/Library/geomagnetism.c
  src/src_user/Library/matrix33.c
  src/src_user/Library/matrix_definition.h
  src/src_user/Library/matrix_user_settings.h
  src/src_user/Library/quaternion.c
  src/src_user/Library/quaternion.h
  src/src_user/Library/time_space.c
  src/src_user/Library/time_space.h
  src/src_user/Settings/Modes/mode_manager_params.h
Labels: :rocket: priority::high, :fish: patch

#174 STTのフッター修正
  src/src_user/Drivers/Aocs/sagitta.c
Labels: :bug: bug, :car: priority::low, :fish: patch

#175 Main merge with resolving conflict
  src/src_user/Applications/DriverInstances/di_mpu9250.c
  src/src_user/Applications/DriverInstances/di_stim210.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/bdot.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/stt_gyro_ekf.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/stt_gyro_ekf.h
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/sun_vector_propagator.h
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/ActuatorControllers/mtq_seiren_controller.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/mpu9250_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/nanossoc_d60_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/oem7600_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/rm3100_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/stim210_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorSelectors/gpsr_selector.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorSelectors/magnetometer_selector.h
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorSelectors/sun_sensor_selector.c
  src/src_user/Applications/UserDefined/AOCS/InertialReference/inertial_geomag_calculator.c
  src/src_user/Applications/UserDefined/AOCS/OrbitEstimation/gpsr_orbit_propagator.c
  src/src_user/Applications/UserDefined/AOCS/TargetAttitude/target_attitude_from_orbit.c
  src/src_user/Applications/UserDefined/AOCS/TargetAttitude/target_attitude_from_orbit.h
  src/src_user/Applications/UserDefined/AOCS/aocs_manager.c
  src/src_user/Applications/UserDefined/AOCS/aocs_manager.h
  src/src_user/Applications/UserDefined/Cdh/non_volatile_memory_manager.h
  src/src_user/Applications/UserDefined/Cdh/non_volatile_memory_parameter.c
  src/src_user/Applications/UserDefined/Power/power_switch_control.c
  src/src_user/Drivers/Aocs/mpu9250.c
  src/src_user/Drivers/Aocs/mpu9250.h
  src/src_user/Drivers/Aocs/mtq_seiren.h
  src/src_user/Drivers/Aocs/oem7600.c
  src/src_user/Drivers/Aocs/oem7600.h
  src/src_user/Drivers/Aocs/rw0003.c
  src/src_user/Drivers/Aocs/stim210.c
  src/src_user/Library/ControlUtility/gyroscopic_effect.h
  src/src_user/Library/Orbit/kepler_orbit.h
  src/src_user/Library/SignalProcess/spike_filter.c
  src/src_user/Library/SignalProcess/z_filter.c
  src/src_user/Library/geomagnetism.c
  src/src_user/Library/matrix33.c
  src/src_user/Library/matrix_definition.h
  src/src_user/Library/matrix_user_settings.h
  src/src_user/Library/quaternion.c
  src/src_user/Library/quaternion.h
  src/src_user/Library/time_space.c
  src/src_user/Library/time_space.h
  src/src_user/Settings/Modes/mode_manager_params.h
Labels: :rocket: priority::high, :fish: patch

#170 STTの大きいテレメ追加
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA1.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA2.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA3.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA4.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA1.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA2.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA3.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA4.csv
  src/src_user/Drivers/Aocs/sagitta.c
  src/src_user/TlmCmd/telemetry_definitions.c
  src/src_user/TlmCmd/telemetry_definitions.h
Labels: :airplane: priority::medium, :dolphin: minor update

#180 Q内挿モードで角度が小さい姿勢変更を自動選択
  database/CmdPlan/AOBC_TARGET_ATTITUDE.ops
  src/src_user/Library/quaternion.c
  src/src_user/Library/quaternion.h
Labels: :airplane: priority::medium, :fish: patch

#179 TimeSystemフォルダ名変更とvcxprojへの追加
  C2A_AOBC.vcxproj
  Examples/C2A_AOBC_EXAMPLE.vcxproj
  src/src_user/Applications/UserDefined/AOCS/aocs_manager.h
  src/src_user/Library/CMakeLists.txt
  src/src_user/Library/TimeSystem/gps_time.c
  src/src_user/Library/TimeSystem/gps_time.h
  src/src_user/Library/time_space.h
Labels: :airplane: priority::medium, :whale: major update

#182 古いgenerate tlm コマンドを新しいものに置換する
  database/CmdPlan/AOBC_ANOMALY.ops
  database/CmdPlan/AOBC_AOCS_MANAGER.ops
  database/CmdPlan/AOBC_BDOT.ops
  database/CmdPlan/AOBC_BIAS.ops
  database/CmdPlan/AOBC_DR.ops
  database/CmdPlan/AOBC_FINE_THREE_AXIS_DETERMINATION.ops
  database/CmdPlan/AOBC_FRAME_TRANSFORMATION.ops
  database/CmdPlan/AOBC_HILS.ops
  database/CmdPlan/AOBC_MODE_MANAGER.ops
  database/CmdPlan/AOBC_MPU9250.ops
  database/CmdPlan/AOBC_MPU9250__FILTER.ops
  database/CmdPlan/AOBC_MTQ_CONTROLLER.ops
  database/CmdPlan/AOBC_NVM.ops
  database/CmdPlan/AOBC_OEM7600.ops
  database/CmdPlan/AOBC_OEM7600_FILTER.ops
  database/CmdPlan/AOBC_ORBIT.ops
  database/CmdPlan/AOBC_RANG_TLM_MODE.ops
  database/CmdPlan/AOBC_RM3100__FILTER.ops
  database/CmdPlan/AOBC_ROUGH_THREE_AXIS_DETERMINATION.ops
  database/CmdPlan/AOBC_RW0003.ops
  database/CmdPlan/AOBC_RW0003_FILTER.ops
  database/CmdPlan/AOBC_SAGITTA_FILTER.ops
  database/CmdPlan/AOBC_SAGITTA_TELEMETRY.ops
  database/CmdPlan/AOBC_STIM210.ops
  database/CmdPlan/AOBC_STIM210__FILTER.ops
  database/CmdPlan/AOBC_STT_GYRO_EKF.ops
  database/CmdPlan/AOBC_SUNSENSOR_FILTER.ops
  database/CmdPlan/AOBC_SUNSENSOR_SELECTOR.ops
  database/CmdPlan/AOBC_SUN_POINTING.ops
  database/CmdPlan/AOBC_TARGET_ATTITUDE.ops
  database/CmdPlan/AOBC_THREE_AXIS_MTQ.ops
  database/CmdPlan/AOBC_THREE_AXIS_RW.ops
  database/CmdPlan/AOBC_TIME_SPACE.ops
  database/CmdPlan/AOBC_UNLOADING.ops
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_start_hk_tlm.c
Labels: :airplane: priority::medium, :dolphin: minor update

#177 粗三軸パラメータをExampleに追加
  Examples/src_aobc_example/Settings/SatelliteParameters/attitude_determination_parameters.c
Labels: :airplane: priority::medium, :fish: patch

#187 AOBC-MOBC 間通信の CRC を有効化
  src/src_user/Drivers/Etc/mobc.c
Labels: :rocket: priority::high, :whale: major update

#188 Sagittaパラメータの追加 xxhashエラー修正
  database/CMD_DB/ISSL6U_AOBC_CMD_DB_CMD_DB.csv
  database/CmdPlan/AOBC_SAGITTA_REAL_SKY_TEST.ops
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA_READ2.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA_SET2.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA_READ2.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_SAGITTA_SET2.csv
  src/src_user/Applications/DriverInstances/di_sagitta.c
  src/src_user/Applications/DriverInstances/di_sagitta.h
  src/src_user/Drivers/Aocs/sagitta.c
  src/src_user/Drivers/Aocs/sagitta.h
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_sagitta.c
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :bug: bug, :rocket: priority::high, :dolphin: minor update

#184 v7.0.0 updateに向けての微修正
  .github/workflows/build.yml
  README.md
Labels: :notebook: documentation, :airplane: priority::medium, :whale: major update

#189 Remove compile-time calculation
  src/src_user/Library/Orbit/sgp4.c
Labels: :bug: bug, :rocket: priority::high, :fish: patch, :wrench: tools

#192 Build as C++ option should default OFF
  CMakeLists.txt
Labels: :airplane: priority::medium, :dolphin: minor update, :wrench: tools

#191 Renovate version in workflow
  .github/workflows/build.yml
  renovate.json
Labels: :airplane: priority::medium, :fish: patch, :wrench: tools

#186 アンローディング目標角速度を軸ごとに設定できるように修正
  Examples/src_aobc_example/Settings/SatelliteParameters/attitude_control_parameters.c
  database/CMD_DB/ISSL6U_AOBC_CMD_DB_CMD_DB.csv
  database/CmdPlan/AOBC_UNLOADING.ops
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_HK_ALGO.csv
  database/TLM_DB/ISSL6U_AOBC_TLM_DB_AOBC_THREE_AXIS_RW.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_HK_ALGO.csv
  database/TLM_DB/calced_data/ISSL6U_AOBC_TLM_DB_AOBC_THREE_AXIS_RW.csv
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/unloading.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/unloading.h
  src/src_user/Settings/SatelliteParameters/Sample/attitude_control_parameters.c
  src/src_user/Settings/SatelliteParameters/attitude_control_parameters.h
  src/src_user/TlmCmd/command_definitions.c
  src/src_user/TlmCmd/command_definitions.h
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :rocket: priority::high, :whale: major update

#181 Bdot遷移前に基準角速度更新
  src/src_user/Applications/UserDefined/AOCS/aocs_mode_manager.c
Labels: :car: priority::low, :fish: patch

#200 Expand DI buffer for STT
  src/src_user/Settings/DriverSuper/driver_super_params.h
Labels: :airplane: priority::medium, :fish: patch

#205 Build as C99 by default
  CMakeLists.txt
  src/src_user/common.cmake
Labels: :airplane: priority::medium, :fish: patch, :wrench: tools

#201 Fix to suit coding rule
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/sun_pointing.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeControl/unloading.c
  src/src_user/Applications/UserDefined/AOCS/AttitudeDetermination/sun_vector_propagator.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/mpu9250_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/nanossoc_d60_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/oem7600_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/rm3100_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/rw0003_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/sagitta_filter.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/SensorFilters/stim210_filter.c
  src/src_user/Applications/UserDefined/AOCS/OrbitEstimation/gpsr_orbit_propagator.c
  src/src_user/Drivers/Aocs/rw0003.c
  src/src_user/Drivers/Aocs/sagitta.c
  src/src_user/IfWrapper/Sils/com_port.cpp
  src/src_user/Settings/SatelliteParameters/Sample/attitude_determination_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/nanossoc_d60_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/structure_parameters.c
  src/src_user/Settings/System/EventHandlerRules/event_handler_rule_hw_oc.c
  src/src_user/Settings/System/EventHandlerRules/event_handler_rule_sw_oc.c
  src/src_user/Settings/git_revision_config.h
Labels: :airplane: priority::medium, :fish: patch, :wrench: tools
