Repository ut-issl/c2a-aobc, pull requests merged in 2024-05, with the labels that each got.

#286 Add BC_AC_OEM7600_UPDATE in TL of Bdot and RSP
  src/src_user/Settings/Modes/TaskLists/tl_bdot.c
  src/src_user/Settings/Modes/TaskLists/tl_rough_sun_pointing.c
Labels: :car: priority::low, :fish: patch

#288 Update STT ON BC
  src/src_user/Settings/Modes/Transitions/sl_fine_three_axis.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_sagitta.c
Labels: :airplane: priority::medium, :fish: patch

#293 Update EL/EH
  src/src_user/Applications/DriverInstances/di_nanossoc_d60.c
  src/src_user/Applications/DriverInstances/di_nanossoc_d60.h
  src/src_user/Applications/DriverInstances/di_oem7600.c
  src/src_user/Applications/DriverInstances/di_oem7600.h
  src/src_user/Applications/DriverInstances/di_rw0003.c
  src/src_user/Applications/DriverInstances/di_rw0003.h
  src/src_user/Applications/DriverInstances/di_sagitta.c
  src/src_user/Applications/DriverInstances/di_sagitta.h
  src/src_user/Applications/DriverInstances/di_stim210.c
  src/src_user/Applications/DriverInstances/di_stim210.h
  src/src_user/Settings/System/EventHandlerRules/event_handler_rule_tlmcmd.c
  src/src_user/Settings/System/EventHandlerRules/event_handler_rules.h
  src/src_user/Settings/System/event_logger_group.h
  src/src_user/Settings/System/event_logger_settings.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_nanossoc_d60.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_oem7600.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_rw0003.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_sagitta.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_stim210.c
Labels: :airplane: priority::medium, :dolphin: minor update

#282 磁気センサバイアスの更新
  src/src_user/Settings/SatelliteParameters/Sample/rm3100_parameters.c
  src/src_user/Settings/SatelliteParameters/nanossoc_d60_parameters.h
  src/src_user/Settings/SatelliteParameters/oem7600_parameters.h
  src/src_user/Settings/SatelliteParameters/sagitta_parameters.h
  src/src_user/Settings/SatelliteParameters/stim210_parameters.h
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_nanossoc_d60.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_oem7600.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_sagitta.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_stim210.c
Labels: :airplane: priority::medium, :dolphin: minor update, :artificial_satellite: C2A

#284 WIP:Rangeテレメの追加
  src/src_user/Applications/DriverInstances/di_oem7600.c
  src/src_user/Drivers/Aocs/oem7600.c
  src/src_user/Drivers/Aocs/oem7600.h
  src/src_user/Settings/DriverSuper/driver_super_params.h
Labels: :airplane: priority::medium, :dolphin: minor update, :artificial_satellite: C2A

#301 STIM210のHW OC閾値緩和
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_stim210.c
Labels: :airplane: priority::medium, :fish: patch

#296 fix MTQ controller behavior in ground test
  src/src_user/Applications/UserDefined/AOCS/ExclusiveControl/magnetic_exclusive_control_timer.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/ActuatorControllers/mtq_seiren_controller.c
  src/src_user/Settings/Modes/TaskLists/Elements/tl_elem_drivers_update.c
  src/src_user/Settings/Modes/TaskLists/tl_initial.c
Labels: :airplane: priority::medium, :fish: patch

#297 add magnetic_exclusive_control_timer->is_enable into tlm
  database/TLM_DB/AOBC_TLM_DB_AOBC_COMPONENTS.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_COMPONENTS.csv
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :airplane: priority::medium, :whale: major update

#305 磁気センサの値反映によるvmicroが動かないバグの修正
  src/src_user/Settings/SatelliteParameters/Sample/nanossoc_d60_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/oem7600_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/sagitta_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/stim210_parameters.c
  src/src_user/Settings/SatelliteParameters/nanossoc_d60_parameters.h
  src/src_user/Settings/SatelliteParameters/oem7600_parameters.h
  src/src_user/Settings/SatelliteParameters/sagitta_parameters.h
  src/src_user/Settings/SatelliteParameters/stim210_parameters.h
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_nanossoc_d60.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_oem7600.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_sagitta.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_stim210.c
Labels: :bug: bug, :rocket: priority::high, :artificial_satellite: C2A

#303 remove tl_gpsr_range_observe.c from vcxproj
  C2A_AOBC.vcxproj
Labels: :bug: bug, :rocket: priority::high, :fish: patch, :artificial_satellite: C2A

#300 SS/STTのDS initをコマンド化しEHを更新
  database/CMD_DB/AOBC_CMD_DB_CMD_DB.csv
  src/src_user/Applications/DriverInstances/di_nanossoc_d60.c
  src/src_user/Applications/DriverInstances/di_nanossoc_d60.h
  src/src_user/Applications/DriverInstances/di_sagitta.c
  src/src_user/Applications/DriverInstances/di_sagitta.h
  src/src_user/Drivers/Aocs/nanossoc_d60.c
  src/src_user/Drivers/Aocs/nanossoc_d60.h
  src/src_user/Drivers/Aocs/sagitta.c
  src/src_user/Drivers/Aocs/sagitta.h
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_nanossoc_d60.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_sagitta.c
  src/src_user/TlmCmd/block_command_definitions.h
  src/src_user/TlmCmd/command_definitions.c
  src/src_user/TlmCmd/command_definitions.h
Labels: :rocket: priority::high, :whale: major update, :artificial_satellite: C2A

#308 Add LPF for angular velocity calculation
  database/CMD_DB/AOBC_CMD_DB_CMD_DB.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_CONTROL.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_CONTROL.csv
  src/src_user/Applications/UserDefined/AOCS/TargetAttitude/target_attitude_calculator.c
  src/src_user/Applications/UserDefined/AOCS/TargetAttitude/target_attitude_calculator.h
  src/src_user/TlmCmd/command_definitions.c
  src/src_user/TlmCmd/command_definitions.h
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :rocket: priority::high, :whale: major update

#309 fix reset timing for torque integration in MTQ controller
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/ActuatorControllers/mtq_seiren_controller.c
  src/src_user/Applications/UserDefined/AOCS/HardwareDependent/ActuatorControllers/mtq_seiren_controller.h
Labels: :bug: bug, :rocket: priority::high, :fish: patch

#311 Sagitta firmware version update to v11.14
  database/CmdPlan/AOBC_SAGITTA_PARAMETER_CHANGE.ops
  database/CmdPlan/AOBC_SAGITTA_PARAMETER_SET.ops
  database/CmdPlan/AOBC_SAGITTA_TELEMETRY.ops
  database/TLM_DB/AOBC_TLM_DB_AOBC_SAGITTA5.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_SAGITTA_READ1.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_SAGITTA_READ2.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_SAGITTA_SET1.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_SAGITTA_SET2.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_SAGITTA5.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_SAGITTA_READ1.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_SAGITTA_READ2.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_SAGITTA_SET1.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_SAGITTA_SET2.csv
  src/src_user/Applications/DriverInstances/di_sagitta.c
  src/src_user/Drivers/Aocs/sagitta.c
  src/src_user/Drivers/Aocs/sagitta.h
  src/src_user/Settings/Modes/Transitions/sl_fine_three_axis.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_sagitta.c
  src/src_user/TlmCmd/telemetry_definitions.c
  src/src_user/TlmCmd/telemetry_definitions.h
Labels: :airplane: priority::medium, :whale: major update

#315 磁気センサバイアス再調整
  src/src_user/Settings/SatelliteParameters/Sample/nanossoc_d60_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/oem7600_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/rm3100_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/sagitta_parameters.c
  src/src_user/Settings/SatelliteParameters/Sample/stim210_parameters.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_oem7600.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_sagitta.c
  src/src_user/TlmCmd/NormalBlockCommandDefinition/nbc_stim210.c
Labels: :rocket: priority::high, :dolphin: minor update, :artificial_satellite: C2A

#316 Fix hard coded RW I2C address
  src/src_user/IfWrapper/Sils/i2c_sils.c
Labels: :bug: bug, :rocket: priority::high, :fish: patch

#318 Add EL low note telemetry
  database/TLM_DB/AOBC_TLM_DB_AOBC_HK_ALGO.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_HK_GEN.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_HK_ALGO.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_HK_GEN.csv
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :car: priority::low, :fish: patch

#320 Add TLC_GS.ERR_COUNTER in HK_GEN
  database/TLM_DB/AOBC_TLM_DB_AOBC_HK_GEN.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_HK_GEN.csv
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :car: priority::low, :fish: patch

#321 Add BC_AC_STIM210_UPDATE in Rough Sun Pointing TL
  src/src_user/Settings/Modes/TaskLists/tl_rough_sun_pointing.c
Labels: :car: priority::low, :fish: patch

#323 Add NaN assertion
  src/src_user/Library/SignalProcess/spike_filter.c
  src/src_user/Library/SignalProcess/z_filter.c
  src/src_user/Library/pid_control.c
Labels: :rocket: priority::high, :dolphin: minor update

#324 main merge from develop for v10.1.0 minor update
  src/src_user/Library/SignalProcess/spike_filter.c
  src/src_user/Library/SignalProcess/z_filter.c
  src/src_user/Library/pid_control.c
Labels: :rocket: priority::high, :dolphin: minor update

#326 [Hotfix] Fix CONTROL telemetry packet
  database/TLM_DB/AOBC_TLM_DB_AOBC_CONTROL.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_CONTROL.csv
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :bug: bug, :rocket: priority::high, :fish: patch

#327 Merge main into develop for hotfix #326
  database/TLM_DB/AOBC_TLM_DB_AOBC_CONTROL.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_CONTROL.csv
  src/src_user/TlmCmd/telemetry_definitions.c
Labels: :rocket: priority::high, :fish: patch
