Repository ut-issl/c2a-aobc, pull requests merged in 2024-04, with the labels that each got.

#278 IGRF計算の修正
  src/src_user/Library/geomagnetism.c
Labels: :bug: bug, :airplane: priority::medium, :dolphin: minor update, :artificial_satellite: C2A

#279 STTのRXバッファを増やす
  src/src_user/Drivers/Aocs/sagitta.c
Labels: :airplane: priority::medium, :fish: patch

#280 RWのfault statusテレメ要求の追加
  database/CMD_DB/AOBC_CMD_DB_CMD_DB.csv
  src/src_user/Applications/DriverInstances/di_rw0003.c
  src/src_user/Applications/DriverInstances/di_rw0003.h
  src/src_user/TlmCmd/command_definitions.c
  src/src_user/TlmCmd/command_definitions.h
Labels: :airplane: priority::medium, :dolphin: minor update

#275 Add Relative Velocity Direction Pointing
  database/CMD_DB/AOBC_CMD_DB_CMD_DB.csv
  database/TLM_DB/AOBC_TLM_DB_AOBC_CONTROL.csv
  database/TLM_DB/calced_data/AOBC_TLM_DB_AOBC_CONTROL.csv
  database/TLM_DB/~$AOBC_TLM_DB.xlsm
  src/src_user/Applications/UserDefined/AOCS/TargetAttitude/target_attitude_from_orbit.c
  src/src_user/Applications/UserDefined/AOCS/TargetAttitude/target_attitude_from_orbit.h
Labels: :airplane: priority::medium, :dolphin: minor update
